name: Tops
version: 1.1.3
main: Tops\Loader
api: ["5.0.0"]
authors:
  - HVNS
description: Leaderboards de Kills, Deaths, Dinero y Tiempo jugado con hologramas por categoria.
load: POSTWORLD

softdepend:
  - BedrockEconomy
  - EconomyAPI

permissions:
  tops.command:
    description: Permite ver el uso del comando /tops
    default: true
  tops.command.spawn:
    description: Permite spawnear un holograma de top
    default: op
  tops.command.despawn:
    description: Permite despawnear un holograma de top
    default: op
  tops.command.reload:
    description: Permite recargar la configuracion del plugin
    default: op
